### ISSUE TITLE
Live Camera Feature -- 10+ Panels multiple gifs

### ISSUE THREAD

**Issue by abigdreamer** [tec27/seatcamp#18]
Live Camera Feature
Button that turns your camera on in real time -- so Your gif alternates from real time whats going on -- to that current gif playback. 

See panels with smaller text (2) views -- Multiple Panels at a time -- maybe 3 across and 3 down
with words underneath in a smaller font.

**Comment by tec27** [comment]
Sorry, I don't think either of those features really fit with what the site is
