### ISSUE TITLE
Turn off webcam capture / video stream when page is in the background

### ISSUE THREAD

**Issue by forivall** [tec27/seatcamp#25]
like #24 , but I'm now pretty sure that the battery usage is from the capture always being active. Also, it means that firefox animates the favicon, which is quite distracting.

**Comment by marcusramberg** [comment]
Seems like #23 fixes that?

**Comment by forivall** [comment]
Yeah, I think so. Thanks @chee!

**Comment by tec27** [comment]
Fixed with #23
