### ISSUE TITLE
Favicon not refreshing on Chrome

### ISSUE THREAD

**Issue by cloudEdwards** [tec27/seatcamp#3]
Hey I am using Chrome and the favicon notification is not updating when I return to the tab. It should disappear, but it stays visible. I should note, that it fails to update to zero new messages, but continues to update new posts, even while I am currently focused on the tab

**Comment by cloudEdwards** [comment]
I have yet to reproduce this in FF, also this bug is intermittent. I will post again if it continues

**Comment by tec27** [comment]
I think this is somewhat related to the pagevisibility API being flaky, but I'm pretty sure I also made this way flakier with my changes to try and give Android a better icon. Turns out that what I did isn't even the best way to do that, so I'll revert that change and do it a different way shortly.

**Comment by tec27** [comment]
Deployed that, should work better now. Re-open if you see it happen again.
