### ISSUE TITLE
Going from portrait to landscape and back in Chrome on Android causes the zoom level go all weird

### ISSUE THREAD

**Issue by alexchally** [tec27/seatcamp#4]
Title pretty much says it all. Everything zooms in when you switch to landscape, but does not unzoom when you switch back to portrait mode. Happens on an N4 and an N5 running latest Chrome,

**Comment by tec27** [comment]
Yeah, weird. Might have to use a different media query or something, I'll take a look.

**Comment by tec27** [comment]
Should be fixed now!

**Comment by alexchally** [comment]
You are a god.
