### ISSUE TITLE
Character counter in text input box does not count characters.

### ISSUE THREAD

**Issue by alexchally** [tec27/seatcamp#7]
How many characters should a character counter count if a character counter should count characters? Probably 255 of them, but the character counter can't count characters so it probably does not matter.

**Comment by tec27** [comment]
I think I had noticed that I broke this and then forgot to fix it, I will do that now :)

Thanks!

**Comment by tec27** [comment]
I'm real bad a programming. Fixed with 1c1fb4bd30036e3321df79e6b08205ef18a01330
